version: "3.9"

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - ATLAS_URI=mongodb+srv://salhianis:E4otExWGyXK4ErEQ@cluster0.u3fu1fg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - PORT=5000
    volumes:
      - ./server:/app
    restart: unless-stopped

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_YOUR_HOSTNAME=http://localhost:5000
    volumes:
      - ./client:/app
    depends_on:
      - server
    restart: unless-stopped
